version: '3.1'

services:

  nginx:
    image: rramachand21/nginx-wp-php-fpm
    ports:
      - 8080:80
    links:
      - wp-fpm
    volumes:
      - wproot:/var/www/html

  wp-fpm:
    tty: true
    stdin_open: true
    image: rramachand21/wp-alpine-php-fpm
    volumes:
      - wproot:/var/www/html
    environment:
      WORDPRESS_DB_HOST: $WP_DB_HOST
      WORDPRESS_DB_USER: $WP_DB_USER
      WORDPRESS_DB_PASSWORD: $WP_DB_PASS
      WPFPM_WP_REDIS_HOST: redis
      WPFPM_RT_WP_NGINX_HELPER_CACHE_PATH: "/tmp/cache"

  redis:
    image: redis:3-alpine

volumes:
  wproot:
